baseURL = 'https://cnwenzhihong.github.io/WzhGameDevPublish'
languageCode = 'zh-CN'
title = '妖精游戏开发馆'
theme = 'hugo-theme-reimu'

defaultContentLanguage = 'zh-CN'
[languages]
[languages.en]
languageName = 'English'
weight = 1
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true


[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
noClasses = false

[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
